[buildPlans.iosevka-wide]                         # <iosevka-wide> is your plan name
family = "Iosevka Wide"                           # Font menu family name
design = ["expanded", "v-asterisk-low", "v-dollar-open", "cv46"]
